[package]
name = "koji"
description = "koji XML-RPC API client"
license = "MIT OR Apache-2.0"
repository = "https://pagure.io/ironthree/koji-rs"

version = "0.0.0"
edition = "2018"

authors = ["Fabio Valentini <decathorpe@gmail.com>"]
readme = "README.md"
categories = ["api-bindings"]
keywords = ["fedora", "koji", "XMLRPC", "client"]


[dependencies]
xmlrpc = "^0.13.1"


[profile.release]
lto = true

