[workspace]
members = [
    "dxr",
    "dxr_derive",
    "dxr_shared",
    "dxr_client",
    "dxr_server",
    "dxr_server_axum",
]

[workspace.package]
version = "0.5.3"
edition = "2021"
rust-version = "1.63.0"
license = "MIT OR Apache-2.0"
authors = ["Fabio Valentini <decathorpe@gmail.com>"]
repository = "https://github.com/ironthree/dxr"

[workspace.dependencies]
dxr_shared = { path = "./dxr_shared", version = "0.5.3" }
dxr_derive = { path = "./dxr_derive", version = "0.5.3" }
dxr_client = { path = "./dxr_client", version = "0.5.3" }
dxr_server = { path = "./dxr_server", version = "0.5.3" }
dxr_server_axum = { path = "./dxr_server_axum", version = "0.5.3" }

[profile.release]
codegen-units = 1
opt-level = 3

