[package]
name = "dxr_server"
description = "Declarative XML-RPC (server implementation)"
categories = ["network-programming", "web-programming::http-client", "encoding"]
keywords = ["XML-RPC", "server"]

license.workspace = true
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]
dxr_shared.workspace = true
async-trait = "0.1.53"
http = "0.2.6"
quick-xml = { version = "0.25" , features = ["serialize"] }

[features]
# support non-standard <i8> XML-RPC values
i8 = ["dxr_shared/i8"]
# support non-standard <nil> XML-RPC values
nil = ["dxr_shared/nil"]

[package.metadata.docs.rs]
all-features = true
