[package]
name = "dxr_server"
description = "Declarative XML-RPC (server implementation)"
license = "MIT OR Apache-2.0"

version = "0.4.0-dev"
edition = "2021"
rust-version = "1.56.0"

authors = ["Fabio Valentini <decathorpe@gmail.com>"]
categories = ["network-programming", "web-programming::http-client", "encoding"]
keywords = ["XML-RPC", "server"]
repository = "https://github.com/ironthree/dxr"
exclude = ["/wip/"]

[dependencies]
anyhow = "1.0.53"
dxr_shared = { path = "../dxr_shared", version = "0.4.0-dev" }
http = "0.2.6"
quick-xml = { version = "0.23" , features = ["serialize"] }

# axum implementation / integration
axum = { version = "0.5.4", optional = true }
tokio = { version = "1.14", optional = true, features = ["sync"] }

[features]
# server implementation based on axum
axum = ["dep:axum", "dep:tokio"]

[package.metadata.docs.rs]
all-features = true
