[package]
name = "dxr"
description = "Declarative XML-RPC"
license = "MIT OR Apache-2.0"

version = "0.1.0"
edition = "2021"
rust-version = "1.56.0"

authors = ["Fabio Valentini <decathorpe@gmail.com>"]
categories = ["network-programming", "web-programming::http-client", "encoding"]
keywords = ["XML-RPC", "client", "derive"]
repository = "https://github.com/ironthree/dxr"

[[example]]
name = "client"
path = "examples/client.rs"
required-features = ["client"]

[[example]]
name = "koji"
path = "examples/koji.rs"
required-features = ["client", "derive"]

[[example]]
name = "server"
path = "examples/server.rs"
required-features = ["server"]

[[test]]
name = "echo"
path = "tests/echo.rs"
required-features = ["derive", "client", "server", "i8", "nil"]

[dependencies]
# default features
dxr_shared = { path = "../dxr_shared", version = "0.1.0" }
log = "0.4.13"
quick-xml = { version = "0.22" , features = ["serialize"] }

# derive feature
dxr_derive = { path = "../dxr_derive", version = "0.1.0", optional = true }

# client feature
reqwest = { version = "0.11", features = ["cookies"] , optional = true }
url = { version = "2.2", optional = true }

# server feature
axum = { version = "0.4.5", optional = true }

[dev-dependencies]
quickcheck = "1.0"
quickcheck_macros = "1.0"
# used for example binaries and integration tests
tokio = { version = "1.14", features = ["macros", "rt-multi-thread"] }
# used for compiling async doctests
tokio-test = "0.4.2"

[features]
default = ["dxr_shared/default", "client", "derive", "i8", "nil"]
client = ["reqwest", "url"]
derive = ["dxr_derive"]
server = ["axum"]
i8 = ["dxr_shared/i8"]
nil = ["dxr_shared/nil"]

[package.metadata.docs.rs]
all-features = true
