[package]
name = "dxr"
description = "Declarative XML-RPC"
license = "MIT OR Apache-2.0"

version = "0.4.0-dev"
edition = "2021"
rust-version = "1.56.0"

authors = ["Fabio Valentini <decathorpe@gmail.com>"]
categories = ["network-programming", "encoding"]
keywords = ["XML-RPC", "client", "server", "derive"]
repository = "https://github.com/ironthree/dxr"
exclude = ["/wip/"]

[[example]]
name = "client"
path = "examples/client.rs"
required-features = ["client"]

[[example]]
name = "koji"
path = "examples/koji.rs"
required-features = ["client", "derive", "nil"]

[[example]]
name = "server"
path = "examples/server.rs"
required-features = ["dxr_server/axum"]

[[test]]
name = "adder"
path = "tests/adder.rs"
required-features = ["client", "dxr_server/axum"]

[[test]]
name = "derive"
path = "tests/derive.rs"
required-features = ["derive", "i8", "nil"]

[[test]]
name = "echo_any"
path = "tests/echo_any.rs"
required-features = ["derive", "client", "server", "dxr_server/axum", "i8", "nil"]

[[test]]
name = "echo_one"
path = "tests/echo_one.rs"
required-features = ["derive", "client", "server", "dxr_server/axum", "i8", "nil"]

[dependencies]
dxr_shared = { path = "../dxr_shared", version = "0.4.0-dev" }
dxr_derive = { path = "../dxr_derive", version = "0.4.0-dev", optional = true }
dxr_client = { path = "../dxr_client", version = "0.4.0-dev", optional = true }
dxr_server = { path = "../dxr_server", version = "0.4.0-dev", optional = true }

[dev-dependencies]
# used for example binaries and integration tests
tokio = { version = "1.14", features = ["macros", "rt-multi-thread", "time"] }

# used to compile and run async code in doctests
tokio-test = "0.4.2"

# used for testing derive macros
trybuild = "1.0.56"

[features]
derive = ["dep:dxr_derive"]
client = ["dep:dxr_client"]
server = ["dxr_server"]

# server: optional axum support code
axum-server = ["server", "dxr_server/axum"]

# support non-standard <i8> XML-RPC values
i8 = ["dxr_shared/i8", "dxr_client?/i8"]
# support non-standard <nil> XML-RPC values
nil = ["dxr_shared/nil", "dxr_client?/nil"]

[package.metadata.docs.rs]
all-features = true
