[package]
name = "dxr"
description = "Declarative XML-RPC"
license = "MIT OR Apache-2.0"

version = "0.0.0"
edition = "2021"
rust-version = "1.56.0"

authors = ["Fabio Valentini <decathorpe@gmail.com>"]
categories = ["network-programming", "web-programming::http-client", "encoding"]
keywords = ["XML-RPC", "client", "derive"]
repository = "https://github.com/ironthree/dxr"

[[example]]
name = "server"
path = "examples/server.rs"
required-features = ["server"]

[dependencies]
axum = { version = "0.4.5", optional = true }
dxr_derive = { path = "../dxr_derive" }
dxr_shared = { path = "../dxr_shared" }
log = "0.4.13"
quick-xml = { version = "0.22" , features = ["serialize"] }
reqwest = { version = "0.11", features = ["cookies"] }
tokio = { version = "1.14", features = ["macros", "rt-multi-thread"] }
url = "2.2"

[dev-dependencies]
tokio = { version = "1.14.0", features = ["macros", "rt-multi-thread"] }

[features]
default = ["dxr_shared/default", "i8", "nil"]
server = ["axum"]
i8 = ["dxr_shared/i8"]
nil = ["dxr_shared/nil"]

