[package]
name = "dxr"
description = "Declarative XML-RPC"
license = "MIT OR Apache-2.0"

version = "0.0.0"
edition = "2021"

authors = ["Fabio Valentini <decathorpe@gmail.com>"]
#readme = "README.md"
#exclude = ["/.github/", "/rustfmt.toml"]
#categories = ["api-bindings"]
#keywords = ["fedora", "koji", "XMLRPC", "client"]
repository = "https://github.com/ironthree/dxr"

[dependencies]
dxr_derive = { path = "../derive" }
dxr_shared = { path = "../shared" }
quick-xml = { version = "0.22" , features = ["serialize"] }
reqwest = { version = "0.11", features = ["cookies"] }
tokio = { version = "1.14", features = ["macros", "rt-multi-thread"] }
url = "2.2"

[features]
default = ["dxr_derive/default", "dxr_shared/default", "i8", "nil"]
i8 = ["dxr_derive/i8", "dxr_shared/i8"]
nil = ["dxr_derive/nil", "dxr_shared/nil"]

